# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='books',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='likes_books.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likes_books.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
